### ISSUE TITLE
Spiderplot facet variables should be distinct

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.osprey#13]
Should you be allowed to select the same variable to facet for both rows and columns?
Or should we add an extra validate here?
![image](https://user-images.githubusercontent.com/12943682/128376813-5710ecc7-03da-41d7-97a6-8ddc26cc2a06.png)

Provenance: 
```
Creator: nikolas-burkoff
```

**Comment by kumamiao** [comment]
Current selection does not make much sense here, extra validate would be nice to have, thanks!

**Comment by Melkiades** [comment]
Should this be closed as it is in "done"?
