### ISSUE TITLE
Add `teal.reporter` into teal.osprey modules

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.osprey#140]

**Comment by junlueZH** [comment]
@kumamiao Could you list the specific encodings that is needed for the modules?

**Comment by kumamiao** [comment]
- Common AE plot, AE overview plot, AE by subgroup, patient profile: 
    - I think the graphics in the plots are rather self-explanatory in terms of the encoding choices, so no need to add additional top section
  - Butterfly:
    - `Preset Data Filters Observations with value of 'Y' for selected variable(s) will be used for analysis`
    - if `Facet By Variable` exists, add it
    - `Sort By Variable`
  - Spider plot:
    - `Parameter - from ADTR`
    - `X-facet By Variable` & `Y-facet By Variable` only if exists
  - Swimlane:
    - `Sort by`
  - Waterfall:
    - `Tumor Burden Parameter`
    - `Sort by` and `Facet by` only if exists
