### ISSUE TITLE
[teal.osprey] Replace validate with relevant shinyvalidate calls

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.osprey#158]
Followup to:
- https://github.com/insightsengineering/coredev-tasks/issues/230

**Comment by gogonzo** [comment]
For example, if you go to the `tm_g_ae_oview`, there is a updateSelectInput on input$arm_var change:

https://github.com/insightsengineering/teal.osprey/blob/88e29b952151b2a615aed1ce2b9051afd1dab452/R/tm_g_ae_oview.R#L244

- we need to validate that variable ANL[[input$arm_var]] is a factor because there is a levels(ANL[[input$arm_var]])
- we no longer need a validate(need like [these](https://github.com/insightsengineering/teal.osprey/blob/88e29b952151b2a615aed1ce2b9051afd1dab452/R/tm_g_ae_oview.R#L274) because validate message should be seen where the input is and not when the output is. 
- in each validation message when condition result can't be controlled by user we should write "Please contact an app developer"

**Comment by BLAZEWIM** [comment]
One question: do we want to validate() message in the output to be the same for every check (like: "Some error in output, observe the red warnings") or different message for each validation? Second option comes with more lines of code, might be considered more elegant, but it is repeating the same info twice

**Comment by gogonzo** [comment]
@BLAZEWIM we don't need the same information twice. iv$is_valid should be probably used to not show output when inputs are not valid

https://rstudio.github.io/shinyvalidate/articles/advanced.html
