### ISSUE TITLE
Remove formatters from package dependencies

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.osprey#219]
Part of https://github.com/insightsengineering/coredev-tasks/issues/447

There are two functions used from formatters
- `formatters::var_labels`
- `formatters::var_relabel`

We should create a copy of this function in `teal.widgets` and export them there.

Acceptance criteria:
- remove formatters from dependencies
- update staged.dependencies.yaml files in all affected packages

**Comment by m7pr** [comment]
Hey, @gogonzo the PR with suggested changes is ready for your review https://github.com/insightsengineering/teal.osprey/pull/220 but if this uses tern maybe we don't need to provide any changes at all. Up to you to accept or close the PR

**Comment by gogonzo** [comment]
@m7pr yup, we can close this issue and related PR based on [this comment](https://github.com/insightsengineering/teal.modules.clinical/issues/794#issuecomment-1641691928)
