### ISSUE TITLE
Fix failed pipeline

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.osprey#279]
https://github.com/pawelru/ie_status?tab=readme-ov-file

**Comment by m7pr** [comment]
- Inability to install dev version of teal.slice during verdepcheck - https://github.com/insightsengineering/teal.osprey/actions/runs/10543905570/job/29212355269#step:9:533
- noSuggests - issue in vignette https://github.com/insightsengineering/teal.osprey/actions/runs/10543905570/job/29212359131#step:8:180

**Comment by m7pr** [comment]
revdepcheck - teal.osprey is not available on CRAN https://github.com/insightsengineering/teal.osprey/actions/runs/10543905570/job/29212354870#step:9:847

**Comment by m7pr** [comment]
For the revdepcheck action there is a conversation going on in here https://github.com/insightsengineering/r-revdepcheck-action/pull/2
