### ISSUE TITLE
Osprey sample app: `AE Overview Plots` filtering resets selected input

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.osprey#9]
UAT of Osprey sample app:
<REDACTED>content/2881/

Applying any filter will reset `Control`, `Treatment` and `Flags` and thus the plot.
TO reproduce:
1) Go to `Adverse Events` -> `AE Overview Plots`
2) Remove some `Flags` and change `Control`
3) Select `AGE` filter and move the slider
4) The changes in 2) will reset.

Provenance: 
```
Creator: mhallal1
```

**Comment by kumamiao** [comment]
No longer applicable, closing
